// import type { Post, Comment, Category } from "./types"
//
// export const mockPosts: Post[] = [
//   {
//     id: 1,
//     title: "Como melhorar a segurança pública no estado?",
//     content:
//       "Gostaria de saber quais são as principais medidas que podem ser tomadas para melhorar a segurança pública em nosso estado. Tenho observado um aumento na criminalidade e acredito que precisamos de ações mais efetivas. Quais são as experiências de outros estados que deram certo? Como podemos implementar essas soluções aqui?",
//     author: "João Silva",
//     isAnonymous: false,
//     createdAt: "2024-01-15T10:30:00Z",
//     votes: 15,
//     commentCount: 8,
//     tags: ["segurança", "política pública"],
//     category: "Segurança",
//     officialResponse: true,
//   },
//   {
//     id: 2,
//     title: "Investimentos em educação: onde focar?",
//     content:
//       "Quais áreas da educação deveriam receber mais investimentos prioritariamente? Vejo que temos problemas tanto na infraestrutura quanto na formação de professores.",
//     author: "Anônimo",
//     isAnonymous: true,
//     createdAt: "2024-01-14T15:45:00Z",
//     votes: 23,
//     commentCount: 12,
//     tags: ["educação", "investimento"],
//     category: "Educação",
//     officialResponse: false,
//   },
//   {
//     id: 3,
//     title: "Transporte público: melhorias necessárias",
//     content:
//       "O transporte público precisa de reformas urgentes. Quais são as prioridades? Os ônibus estão sempre lotados e atrasados.",
//     author: "Maria Santos",
//     isAnonymous: false,
//     createdAt: "2024-01-13T09:20:00Z",
//     votes: 7,
//     commentCount: 5,
//     tags: ["transporte", "infraestrutura"],
//     category: "Transporte",
//     officialResponse: true,
//   },
//   {
//     id: 4,
//     title: "Programa de saúde preventiva",
//     content:
//       "Como podemos implementar um programa mais efetivo de saúde preventiva no estado? A prevenção é sempre mais barata que o tratamento.",
//     author: "Dr. Carlos Mendes",
//     isAnonymous: false,
//     createdAt: "2024-01-12T14:15:00Z",
//     votes: 18,
//     commentCount: 9,
//     tags: ["saúde", "prevenção"],
//     category: "Saúde",
//     officialResponse: false,
//   },
//   {
//     id: 5,
//     title: "Incentivos para pequenas empresas",
//     content: "Que tipo de incentivos o governo poderia oferecer para fortalecer as pequenas empresas locais?",
//     author: "Anônimo",
//     isAnonymous: true,
//     createdAt: "2024-01-11T11:30:00Z",
//     votes: 12,
//     commentCount: 6,
//     tags: ["economia", "pequenas empresas"],
//     category: "Economia",
//     officialResponse: true,
//   },
// ]
//
// export const mockComments: { [postId: number]: Comment[] } = {
//   1: [
//     {
//       id: 1,
//       content:
//         "Acredito que o investimento em policiamento comunitário seria uma boa estratégia. Isso aproxima a polícia da comunidade e cria vínculos de confiança.",
//       author: "Maria Santos",
//       isAnonymous: false,
//       createdAt: "2024-01-15T11:00:00Z",
//       votes: 5,
//       isOfficial: false,
//       replies: [
//         {
//           id: 4,
//           content:
//             "Concordo! O policiamento comunitário tem mostrado resultados positivos em outras regiões. Já vi casos de sucesso em São Paulo.",
//           author: "Pedro Lima",
//           isAnonymous: false,
//           createdAt: "2024-01-15T11:30:00Z",
//           votes: 2,
//           isOfficial: false,
//           replies: [],
//         },
//       ],
//     },
//     {
//       id: 2,
//       content:
//         "Prezado João, sua pergunta é muito pertinente. Estamos trabalhando em um plano abrangente que inclui: 1) Aumento do efetivo policial em 20%, 2) Modernização dos equipamentos e viaturas, 3) Programas de prevenção social focados na juventude, 4) Parcerias com a comunidade através de conselhos de segurança. Em breve divulgaremos mais detalhes sobre essas iniciativas e o cronograma de implementação.",
//       author: "Gabinete Wyden",
//       isAnonymous: false,
//       createdAt: "2024-01-15T14:00:00Z",
//       votes: 12,
//       isOfficial: true,
//       replies: [],
//     },
//     {
//       id: 3,
//       content:
//         "É importante também investir em educação e programas sociais para prevenir a criminalidade. A segurança não se resolve apenas com policiamento.",
//       author: "Anônimo",
//       isAnonymous: true,
//       createdAt: "2024-01-15T12:00:00Z",
//       votes: 8,
//       isOfficial: false,
//       replies: [],
//     },
//   ],
// }
//
// export const mockCategories: Category[] = [
//   {
//     id: 1,
//     name: "Segurança",
//     description: "Discussões sobre segurança pública, policiamento e prevenção à criminalidade",
//     icon: "🛡️",
//     postCount: 45,
//     color: "bg-red-100 text-red-700",
//   },
//   {
//     id: 2,
//     name: "Educação",
//     description: "Tópicos sobre ensino, infraestrutura escolar e formação de professores",
//     icon: "📚",
//     postCount: 67,
//     color: "bg-blue-100 text-blue-700",
//   },
//   {
//     id: 3,
//     name: "Saúde",
//     description: "Questões relacionadas à saúde pública, hospitais e programas preventivos",
//     icon: "🏥",
//     postCount: 52,
//     color: "bg-green-100 text-green-700",
//   },
//   {
//     id: 4,
//     name: "Transporte",
//     description: "Melhorias no transporte público, infraestrutura viária e mobilidade urbana",
//     icon: "🚌",
//     postCount: 38,
//     color: "bg-yellow-100 text-yellow-700",
//   },
//   {
//     id: 5,
//     name: "Economia",
//     description: "Desenvolvimento econômico, incentivos fiscais e apoio a empresas",
//     icon: "💼",
//     postCount: 41,
//     color: "bg-purple-100 text-purple-700",
//   },
//   {
//     id: 6,
//     name: "Meio Ambiente",
//     description: "Sustentabilidade, preservação ambiental e políticas ecológicas",
//     icon: "🌱",
//     postCount: 29,
//     color: "bg-emerald-100 text-emerald-700",
//   },
//   {
//     id: 7,
//     name: "Cultura",
//     description: "Eventos culturais, patrimônio histórico e incentivo às artes",
//     icon: "🎭",
//     postCount: 23,
//     color: "bg-pink-100 text-pink-700",
//   },
//   {
//     id: 8,
//     name: "Tecnologia",
//     description: "Inovação, transformação digital e inclusão tecnológica",
//     icon: "💻",
//     postCount: 34,
//     color: "bg-indigo-100 text-indigo-700",
//   },
// ]
//
// export const mockPostsByCategory: { [categoryId: number]: Post[] } = {
//   1: [
//     // Segurança
//     {
//       id: 101,
//       title: "Como melhorar a segurança pública no estado?",
//       content:
//         "Gostaria de saber quais são as principais medidas que podem ser tomadas para melhorar a segurança pública em nosso estado. Tenho observado um aumento na criminalidade e acredito que precisamos de ações mais efetivas.",
//       author: "João Silva",
//       isAnonymous: false,
//       createdAt: "2024-01-15T10:30:00Z",
//       votes: 15,
//       commentCount: 8,
//       tags: ["segurança", "política pública"],
//       category: "Segurança",
//       officialResponse: true,
//     },
//     {
//       id: 102,
//       title: "Policiamento comunitário funciona?",
//       content:
//         "Tenho visto discussões sobre policiamento comunitário. Alguém sabe se isso realmente funciona? Quais são os resultados práticos?",
//       author: "Anônimo",
//       isAnonymous: true,
//       createdAt: "2024-01-14T14:20:00Z",
//       votes: 8,
//       commentCount: 5,
//       tags: ["segurança", "policiamento"],
//       category: "Segurança",
//       officialResponse: false,
//     },
//     {
//       id: 103,
//       title: "Iluminação pública e segurança",
//       content:
//         "Meu bairro está muito escuro à noite. Acredito que melhorar a iluminação pública ajudaria muito na segurança. Como podemos solicitar isso?",
//       author: "Maria Santos",
//       isAnonymous: false,
//       createdAt: "2024-01-13T16:45:00Z",
//       votes: 12,
//       commentCount: 4,
//       tags: ["segurança", "infraestrutura"],
//       category: "Segurança",
//       officialResponse: false,
//     },
//   ],
//   2: [
//     // Educação
//     {
//       id: 201,
//       title: "Investimentos em educação: onde focar?",
//       content:
//         "Quais áreas da educação deveriam receber mais investimentos prioritariamente? Vejo que temos problemas tanto na infraestrutura quanto na formação de professores.",
//       author: "Anônimo",
//       isAnonymous: true,
//       createdAt: "2024-01-14T15:45:00Z",
//       votes: 23,
//       commentCount: 12,
//       tags: ["educação", "investimento"],
//       category: "Educação",
//       officialResponse: false,
//     },
//     {
//       id: 202,
//       title: "Qualidade do ensino público",
//       content:
//         "Como podemos melhorar a qualidade do ensino nas escolas públicas? Meus filhos estudam em escola pública e vejo muitas deficiências.",
//       author: "Carlos Mendes",
//       isAnonymous: false,
//       createdAt: "2024-01-13T09:30:00Z",
//       votes: 18,
//       commentCount: 9,
//       tags: ["educação", "ensino público"],
//       category: "Educação",
//       officialResponse: true,
//     },
//     {
//       id: 203,
//       title: "Formação continuada de professores",
//       content:
//         "Os professores precisam de mais oportunidades de formação continuada. Que programas existem ou poderiam ser criados?",
//       author: "Ana Paula",
//       isAnonymous: false,
//       createdAt: "2024-01-12T11:15:00Z",
//       votes: 14,
//       commentCount: 7,
//       tags: ["educação", "professores"],
//       category: "Educação",
//       officialResponse: false,
//     },
//   ],
//   3: [
//     // Saúde
//     {
//       id: 301,
//       title: "Programa de saúde preventiva",
//       content:
//         "Como podemos implementar um programa mais efetivo de saúde preventiva no estado? A prevenção é sempre mais barata que o tratamento.",
//       author: "Dr. Carlos Mendes",
//       isAnonymous: false,
//       createdAt: "2024-01-12T14:15:00Z",
//       votes: 18,
//       commentCount: 9,
//       tags: ["saúde", "prevenção"],
//       category: "Saúde",
//       officialResponse: false,
//     },
//     {
//       id: 302,
//       title: "Tempo de espera nos hospitais",
//       content:
//         "O tempo de espera nos hospitais públicos está insuportável. Já esperei mais de 6 horas para ser atendido. O que pode ser feito?",
//       author: "Anônimo",
//       isAnonymous: true,
//       createdAt: "2024-01-11T08:30:00Z",
//       votes: 25,
//       commentCount: 15,
//       tags: ["saúde", "hospitais"],
//       category: "Saúde",
//       officialResponse: true,
//     },
//     {
//       id: 303,
//       title: "Vacinação infantil",
//       content:
//         "Como está a cobertura vacinal infantil no estado? Tenho visto notícias preocupantes sobre a queda nas taxas de vacinação.",
//       author: "Paula Oliveira",
//       isAnonymous: false,
//       createdAt: "2024-01-10T13:20:00Z",
//       votes: 11,
//       commentCount: 6,
//       tags: ["saúde", "vacinação"],
//       category: "Saúde",
//       officialResponse: false,
//     },
//   ],
//   4: [
//     // Transporte
//     {
//       id: 401,
//       title: "Transporte público: melhorias necessárias",
//       content:
//         "O transporte público precisa de reformas urgentes. Quais são as prioridades? Os ônibus estão sempre lotados e atrasados.",
//       author: "Maria Santos",
//       isAnonymous: false,
//       createdAt: "2024-01-13T09:20:00Z",
//       votes: 7,
//       commentCount: 5,
//       tags: ["transporte", "infraestrutura"],
//       category: "Transporte",
//       officialResponse: true,
//     },
//     {
//       id: 402,
//       title: "Ciclovias na cidade",
//       content:
//         "Precisamos de mais ciclovias! O uso de bicicletas poderia reduzir o trânsito e melhorar a qualidade do ar. Quando teremos mais ciclovias?",
//       author: "Pedro Lima",
//       isAnonymous: false,
//       createdAt: "2024-01-12T10:45:00Z",
//       votes: 16,
//       commentCount: 8,
//       tags: ["transporte", "mobilidade"],
//       category: "Transporte",
//       officialResponse: false,
//     },
//     {
//       id: 403,
//       title: "Tarifa do transporte público",
//       content:
//         "A tarifa do ônibus está muito cara para a qualidade do serviço oferecido. Existe algum estudo sobre reajuste ou melhoria do serviço?",
//       author: "Anônimo",
//       isAnonymous: true,
//       createdAt: "2024-01-11T15:30:00Z",
//       votes: 20,
//       commentCount: 11,
//       tags: ["transporte", "tarifa"],
//       category: "Transporte",
//       officialResponse: false,
//     },
//   ],
//   5: [
//     // Economia
//     {
//       id: 501,
//       title: "Incentivos para pequenas empresas",
//       content: "Que tipo de incentivos o governo poderia oferecer para fortalecer as pequenas empresas locais?",
//       author: "Anônimo",
//       isAnonymous: true,
//       createdAt: "2024-01-11T11:30:00Z",
//       votes: 12,
//       commentCount: 6,
//       tags: ["economia", "pequenas empresas"],
//       category: "Economia",
//       officialResponse: true,
//     },
//     {
//       id: 502,
//       title: "Geração de empregos",
//       content: "Quais são os planos para gerar mais empregos no estado? A taxa de desemprego está preocupante.",
//       author: "Roberto Silva",
//       isAnonymous: false,
//       createdAt: "2024-01-10T09:15:00Z",
//       votes: 19,
//       commentCount: 10,
//       tags: ["economia", "emprego"],
//       category: "Economia",
//       officialResponse: false,
//     },
//     {
//       id: 503,
//       title: "Turismo local",
//       content:
//         "Como podemos desenvolver o turismo local? Temos muitos pontos turísticos que poderiam ser mais explorados.",
//       author: "Fernanda Costa",
//       isAnonymous: false,
//       createdAt: "2024-01-09T14:20:00Z",
//       votes: 9,
//       commentCount: 4,
//       tags: ["economia", "turismo"],
//       category: "Economia",
//       officialResponse: false,
//     },
//   ],
//   6: [
//     // Meio Ambiente
//     {
//       id: 601,
//       title: "Coleta seletiva de lixo",
//       content:
//         "A coleta seletiva não funciona direito no meu bairro. Como podemos melhorar isso? A reciclagem é importante!",
//       author: "Lucas Martins",
//       isAnonymous: false,
//       createdAt: "2024-01-12T08:45:00Z",
//       votes: 13,
//       commentCount: 7,
//       tags: ["meio ambiente", "reciclagem"],
//       category: "Meio Ambiente",
//       officialResponse: false,
//     },
//     {
//       id: 602,
//       title: "Preservação de áreas verdes",
//       content: "Estão derrubando árvores no parque perto da minha casa. Como podemos proteger nossas áreas verdes?",
//       author: "Anônimo",
//       isAnonymous: true,
//       createdAt: "2024-01-11T16:30:00Z",
//       votes: 22,
//       commentCount: 13,
//       tags: ["meio ambiente", "preservação"],
//       category: "Meio Ambiente",
//       officialResponse: true,
//     },
//     {
//       id: 603,
//       title: "Energia renovável",
//       content:
//         "Quais são os planos para investir em energia renovável no estado? Precisamos pensar no futuro sustentável.",
//       author: "Marina Souza",
//       isAnonymous: false,
//       createdAt: "2024-01-10T12:00:00Z",
//       votes: 15,
//       commentCount: 8,
//       tags: ["meio ambiente", "energia"],
//       category: "Meio Ambiente",
//       officialResponse: false,
//     },
//   ],
//   7: [
//     // Cultura
//     {
//       id: 701,
//       title: "Eventos culturais gratuitos",
//       content:
//         "Precisamos de mais eventos culturais gratuitos na cidade. Música, teatro, cinema... Como podemos ter mais opções?",
//       author: "Juliana Alves",
//       isAnonymous: false,
//       createdAt: "2024-01-13T17:30:00Z",
//       votes: 17,
//       commentCount: 9,
//       tags: ["cultura", "eventos"],
//       category: "Cultura",
//       officialResponse: false,
//     },
//     {
//       id: 702,
//       title: "Preservação do patrimônio histórico",
//       content:
//         "Vários prédios históricos estão em péssimo estado de conservação. O que está sendo feito para preservar nosso patrimônio?",
//       author: "Ricardo Mendes",
//       isAnonymous: false,
//       createdAt: "2024-01-12T13:45:00Z",
//       votes: 10,
//       commentCount: 5,
//       tags: ["cultura", "patrimônio"],
//       category: "Cultura",
//       officialResponse: true,
//     },
//     {
//       id: 703,
//       title: "Apoio a artistas locais",
//       content: "Como o governo pode apoiar mais os artistas locais? Temos muito talento que precisa de incentivo.",
//       author: "Anônimo",
//       isAnonymous: true,
//       createdAt: "2024-01-11T10:20:00Z",
//       votes: 14,
//       commentCount: 6,
//       tags: ["cultura", "artistas"],
//       category: "Cultura",
//       officialResponse: false,
//     },
//   ],
//   8: [
//     // Tecnologia
//     {
//       id: 801,
//       title: "Internet nas escolas",
//       content:
//         "Muitas escolas ainda não têm internet de qualidade. Como podemos resolver isso? A tecnologia é essencial para a educação moderna.",
//       author: "Professor João",
//       isAnonymous: false,
//       createdAt: "2024-01-14T11:30:00Z",
//       votes: 21,
//       commentCount: 11,
//       tags: ["tecnologia", "educação"],
//       category: "Tecnologia",
//       officialResponse: false,
//     },
//     {
//       id: 802,
//       title: "Governo digital",
//       content:
//         "Quando teremos mais serviços públicos disponíveis online? Seria muito mais prático não precisar ir presencialmente para tudo.",
//       author: "Anônimo",
//       isAnonymous: true,
//       createdAt: "2024-01-13T14:15:00Z",
//       votes: 26,
//       commentCount: 14,
//       tags: ["tecnologia", "governo digital"],
//       category: "Tecnologia",
//       officialResponse: true,
//     },
//     {
//       id: 803,
//       title: "Inclusão digital para idosos",
//       content: "Meus pais têm dificuldade com tecnologia. Existem programas de inclusão digital para a terceira idade?",
//       author: "Carla Rodrigues",
//       isAnonymous: false,
//       createdAt: "2024-01-12T09:45:00Z",
//       votes: 18,
//       commentCount: 8,
//       tags: ["tecnologia", "inclusão"],
//       category: "Tecnologia",
//       officialResponse: false,
//     },
//   ],
// }
